// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	saveApiKey: (provider: ProviderId, apiKey: string) => typedError<null, AppError>(__TAURI_INVOKE("save_api_key", { provider, apiKey })),
	deleteApiKey: (provider: ProviderId) => typedError<null, AppError>(__TAURI_INVOKE("delete_api_key", { provider })),
	hasApiKey: (provider: ProviderId) => typedError<boolean, AppError>(__TAURI_INVOKE("has_api_key", { provider })),
	listProviders: () => typedError<ProviderStatus[], AppError>(__TAURI_INVOKE("list_providers")),
	testProviderConnection: (provider: ProviderId) => typedError<null, AppError>(__TAURI_INVOKE("test_provider_connection", { provider })),
	listModels: (provider: ProviderId) => typedError<ModelInfo[], AppError>(__TAURI_INVOKE("list_models", { provider })),
	runGeneration: (input: RunGenerationInput) => typedError<Run_Serialize, AppError>(__TAURI_INVOKE("run_generation", { input })),
};

/* Types */
/**
 *  The app's single domain-level error type.
 * 
 *  Each variant carries an already-fully-formatted message — callers build the whole sentence
 *  at the point where they have the context to make it useful (e.g. `format!("OpenAI request
 *  failed: {e}")`), rather than this type gluing a generic prefix onto a fragment. This keeps
 *  `Display` (via thiserror, for logs and internal `?` conversions), `Serialize`, and
 *  `specta::Type` (for the generated TypeScript bindings) all in agreement automatically: they
 *  all just read the same `#[serde(tag = "kind", content = "message")]` shape, with no
 *  hand-written impl needed.
 */
export type AppError = { kind: "Provider"; message: string } | { kind: "Storage"; message: string } | { kind: "Secret"; message: string } | { kind: "NotFound"; message: string } | { kind: "InvalidInput"; message: string };

/**
 *  Identifies an `Experiment` (a group of Runs — see docs/start.md). The full `Experiment`
 *  domain type is introduced when side-by-side comparison is implemented; `Run` only needs the
 *  id to record which experiment, if any, it belongs to.
 */
export type ExperimentId = ExperimentId_Serialize | ExperimentId_Deserialize;

/**
 *  Identifies an `Experiment` (a group of Runs — see docs/start.md). The full `Experiment`
 *  domain type is introduced when side-by-side comparison is implemented; `Run` only needs the
 *  id to record which experiment, if any, it belongs to.
 */
export type ExperimentId_Deserialize = string;

/**
 *  Identifies an `Experiment` (a group of Runs — see docs/start.md). The full `Experiment`
 *  domain type is introduced when side-by-side comparison is implemented; `Run` only needs the
 *  id to record which experiment, if any, it belongs to.
 */
export type ExperimentId_Serialize = string;

/**
 *  Generation parameters as configured by the user for a Run.
 * 
 *  Every field is optional: the frontend only sets the ones a model's `ModelCapabilities`
 *  mark as supported, and a provider module only includes the fields its API accepts when
 *  building the actual HTTP request.
 */
export type GenerationParams = {
	temperature: number | null,
	top_p: number | null,
	max_tokens: number | null,
};

/**
 *  Which generation parameters a given model actually supports.
 * 
 *  The UI uses this to decide which controls to show — see docs/start.md: "Ne force pas
 *  l'affichage d'un paramètre qu'un fournisseur ou un modèle ne supporte pas." Pricing and
 *  context window are handled separately (see `pricing/`, added in a later step) so that the
 *  pricing table can be updated independently of this registry.
 */
export type ModelCapabilities = {
	supports_temperature: boolean,
	supports_top_p: boolean,
	supports_max_tokens: boolean,
	/**
	 *  Whether the provider integration can stream this model's output. Not used until
	 *  streaming is implemented, but part of the shape from day one (see docs/start.md's
	 *  streaming section).
	 */
	supports_streaming: boolean,
};

/**
 *  A model available from a given provider, along with what it supports.
 * 
 *  Instances come from the Model Registry (a later step): either fetched dynamically from a
 *  provider's API and cached, or from a small bundled static list for providers/models that
 *  don't expose one.
 */
export type ModelInfo = {
	provider: ProviderId,
	/**  The exact identifier the provider's API expects, e.g. `"gpt-4o-mini"`. */
	model_id: string,
	/**  Human-readable name for the UI, e.g. `"GPT-4o mini"`. */
	display_name: string,
	capabilities: ModelCapabilities,
	/**  Context window size in tokens, when known. */
	context_window: number | null,
};

/**
 *  Identifies which LLM provider a model, API key, or Run belongs to.
 * 
 *  This is a closed enum (not a free-form string) so the compiler catches typos and a future
 *  `ProviderRegistry` can exhaustively match over every known provider. Adding a new provider
 *  means adding a variant here plus a new module under `providers/` — nothing else needs to
 *  change.
 */
export type ProviderId = "openai" | "anthropic" | "gemini" | "mistral" | "openrouter" | "openai_compatible";

/**
 *  One provider's status for the Settings screen: whether PromptRig has an implementation for
 *  it yet, and whether the user has configured a key for it.
 */
export type ProviderStatus = {
	provider: ProviderId,
	display_name: string,
	implemented: boolean,
	configured: boolean,
};

/**
 *  A single execution of Provider + Model + System Prompt + User Prompt + parameters.
 * 
 *  A Run is the atomic unit the whole app is built around: a solo Playground execution is a Run
 *  with `experiment_id: None`, and a side-by-side comparison is simply several Runs sharing the
 *  same `experiment_id`. The side-by-side UI (a later step) introduces no separate "comparison"
 *  concept in the domain — it's just multiple Runs.
 */
export type Run = Run_Serialize | Run_Deserialize;

/**
 *  What the frontend sends to run one generation. Mirrors `Run`'s "request" half — the
 *  "result" half gets filled in here after calling the provider.
 */
export type RunGenerationInput = {
	provider: ProviderId,
	model_id: string,
	system_prompt: string,
	user_prompt: string,
	params: GenerationParams,
};

/**
 *  Identifies a `Run` once it has been persisted.
 * 
 *  Wrapping the raw `i64` (SQLite's rowid) in a newtype stops us from accidentally passing a
 *  `RunId` where an `ExperimentId` (or any other bare integer) was expected — the compiler will
 *  reject it. Assigning the actual value is the storage layer's job.
 */
export type RunId = RunId_Serialize | RunId_Deserialize;

/**
 *  Identifies a `Run` once it has been persisted.
 * 
 *  Wrapping the raw `i64` (SQLite's rowid) in a newtype stops us from accidentally passing a
 *  `RunId` where an `ExperimentId` (or any other bare integer) was expected — the compiler will
 *  reject it. Assigning the actual value is the storage layer's job.
 */
export type RunId_Deserialize = string;

/**
 *  Identifies a `Run` once it has been persisted.
 * 
 *  Wrapping the raw `i64` (SQLite's rowid) in a newtype stops us from accidentally passing a
 *  `RunId` where an `ExperimentId` (or any other bare integer) was expected — the compiler will
 *  reject it. Assigning the actual value is the storage layer's job.
 */
export type RunId_Serialize = string;

/**
 *  What a provider's `generate()` call returns on success.
 * 
 *  This is deliberately separate from `Run`: `RunResult` is just "what came back from the API
 *  call", while `Run` is the full persisted record (request + result). Keeping them separate
 *  means a provider implementation never needs to know about `Experiment`s, ids, or storage.
 */
export type RunResult = {
	text: string,
	/**  `None` when the provider's response didn't include usage information. */
	usage: Usage | null,
	/**
	 *  `u32` is plenty for a millisecond duration (up to ~49 days) and, unlike `u64`, is safe to
	 *  export straight to TypeScript (see `id_as_string` above for why that distinction matters).
	 */
	duration_ms: number,
	/**  Time to first token. `None` until streaming is implemented (see docs/start.md). */
	ttft_ms: number | null,
};

/**
 *  A single execution of Provider + Model + System Prompt + User Prompt + parameters.
 * 
 *  A Run is the atomic unit the whole app is built around: a solo Playground execution is a Run
 *  with `experiment_id: None`, and a side-by-side comparison is simply several Runs sharing the
 *  same `experiment_id`. The side-by-side UI (a later step) introduces no separate "comparison"
 *  concept in the domain — it's just multiple Runs.
 */
export type Run_Deserialize = {
	id: RunId_Deserialize,
	experiment_id: ExperimentId_Deserialize | null,
	provider: ProviderId,
	model_id: string,
	system_prompt: string,
	user_prompt: string,
	params: GenerationParams,
	started_at: string,
	/**  Present when the call succeeded. Mutually exclusive with `error`. */
	result: RunResult | null,
	/**  Present when the call failed. Mutually exclusive with `result`. */
	error: string | null,
	/**
	 *  Estimated cost in USD, computed from `result.usage` by the pricing module (a later step).
	 *  `None` when there's no usage yet, or no pricing data for this model.
	 */
	estimated_cost_usd: number | null,
};

/**
 *  A single execution of Provider + Model + System Prompt + User Prompt + parameters.
 * 
 *  A Run is the atomic unit the whole app is built around: a solo Playground execution is a Run
 *  with `experiment_id: None`, and a side-by-side comparison is simply several Runs sharing the
 *  same `experiment_id`. The side-by-side UI (a later step) introduces no separate "comparison"
 *  concept in the domain — it's just multiple Runs.
 */
export type Run_Serialize = {
	id: RunId_Serialize,
	experiment_id: ExperimentId_Serialize | null,
	provider: ProviderId,
	model_id: string,
	system_prompt: string,
	user_prompt: string,
	params: GenerationParams,
	started_at: string,
	/**  Present when the call succeeded. Mutually exclusive with `error`. */
	result: RunResult | null,
	/**  Present when the call failed. Mutually exclusive with `result`. */
	error: string | null,
	/**
	 *  Estimated cost in USD, computed from `result.usage` by the pricing module (a later step).
	 *  `None` when there's no usage yet, or no pricing data for this model.
	 */
	estimated_cost_usd: number | null,
};

/**  Token counts reported by a provider for one generation call. */
export type Usage = {
	input_tokens: number,
	output_tokens: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

